spring:
  application:
    name: springflix-webui
  cloud:
    refresh:
      enabled: false
    loadbalancer:
      eager-load:
        clients:
        - springflix-gateway
    discovery:
      client:
        simple:
          instances:
            springflix-gateway:
            - uri: http://localhost:8080
  web:
    resources:
      cache:
        cache-control:
          max-age: 1d

server:
  port: ${PORT:9000}
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: "*"
