app:
  services:
    gateway: http://localhost:8080

spring:
  application:
    name: springflix-webui
  cloud:
    refresh:
      enabled: false
    loadbalancer:
      eager-load:
        clients:
        - springflix-gateway
    discovery:
      client:
        simple:
          instances:
            springflix-gateway:
            - uri: ${app.services.gateway}
  web:
    resources:
      cache:
        cache-control:
          max-age: 1d

server:
  port: ${PORT:9000}
  forward-headers-strategy: native

management:
  observations:
    key-values: &tags
      application: springflix
      service: ${spring.application.name}
      source: ${spring.application.name}-${random.uuid}
  metrics:
    tags: *tags
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        step: 30s
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    io:
      micrometer:
        registry:
          otlp: off
      opentelemetry:
        exporter:
          internal:
            http: off
